script: 'ci/travis.rb'
rvm:
  - ruby-head
  - 1.9.3
  - jruby-19mode
  - jruby-head
  - rbx-19mode
  - 2.0.0
  - 2.1.0
gemfile:
  - Gemfile
notifications:
  email:
    recipients:
      - Martin.Bosslet@googlemail.com
    on_success: always
    on_failure: always
branches:
  only:
    - master
